name: CD

on:
  workflow_call:
    inputs:
      artifacts-path:
        type: string
        required: false
        default: build/libs
        description: Artifacts path, default is build/libs. Must be a folder.
      ui-path:
        description: Path of UI project.
        type: string
        required: false
        default: "console"
      app-id:
        description: Application ID from Halo Appstore.
        required: true
        type: string
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment
        uses: halo-sigs/actions/plugin-setup-env@v1.0
        with:
          cache-dept-path: ${{ inputs.ui-path }}/pnpm-lock.yaml
      - name: Build
        run: ./gradlew build -x check
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ${{ inputs.artifacts-path }}
          retention-days: 1

  github-release:
    name: GitHub Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: ${{ inputs.artifacts-path }}
      - name: Upload Release Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ${{ inputs.artifacts-path }}/*
  appstore-release:
    name: Appstore Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: ${{ inputs.artifacts-path }}
      - name: Release to Appstore
        uses: halo-sigs/app-store-release-action@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          app-id: ${{ inputs.app-id }}
          # TODO Remove the baseurl before releasing
          halo-backend-baseurl: https://halo-dev.ryanc.cc
          release-id: ${{ github.event.release.id }}
          assets-dir: ${{ inputs.artifacts-path }}
          halo-username: ${{ secrets.HALO_USERNAME }}
          halo-password: ${{ secrets.HALO_PASSWORD }}
